version: '3.8'
services:
  backend-staging:
    build: 
      context: ../../task-manager/backend
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=staging
      - PORT=5000
    restart: unless-stopped

  frontend-staging:
    build: ../../task-manager/frontend
    ports:
      - "3002:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5002
      - REACT_APP_ENV=staging
    depends_on:
      - backend-staging
    restart: unless-stopped
