version: '3.8'
services:
  backend-prod:
    build: 
      context: ../../task-manager/backend
    ports:
      - "5003:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped

  frontend-prod:
    build: ../../task-manager/frontend
    ports:
      - "3003:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5003
      - REACT_APP_ENV=production
    depends_on:
      - backend-prod
    restart: unless-stopped
