version: '3.8'
services:
  backend-dev:
    build: 
      context: ../../task-manager/backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ../../task-manager/backend:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  frontend-dev:
    build: 
      context: ../../task-manager/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - REACT_APP_ENV=development
    volumes:
      - ../../task-manager/frontend/src:/app/src
    depends_on:
      - backend-dev
    restart: unless-stopped
